"""Regression tests for the four :class:`PydanticJSON` defects.

Each test here corresponds to a defect that was verified against SQLAlchemy 2.0.52
before being fixed. They are pure-logic tests: no database is required to observe a
cache key, an ``adapt()`` result, or a dialect impl.
"""

from __future__ import annotations

from typing import Annotated, Final, Literal

import pytest
from pydantic import BaseModel, Field, TypeAdapter
from sqlalchemy.dialects import postgresql

from hypervigilant.db.types import NAMING_CONVENTION, PydanticJSON, build_metadata

pytestmark = pytest.mark.unit


class Alpha(BaseModel):
    kind: Literal["alpha"] = "alpha"
    value: int


class Beta(BaseModel):
    kind: Literal["beta"] = "beta"
    label: str


type Variant = Annotated[Alpha | Beta, Field(discriminator="kind")]

VARIANT_ADAPTER: Final = TypeAdapter[Variant](Variant)
ALPHA_ADAPTER: Final = TypeAdapter(Alpha)
BETA_ADAPTER: Final = TypeAdapter(Beta)


def test_cache_key_distinguishes_adapters() -> None:
    """Two columns carrying different Pydantic types must not share a cache key.

    The defect: the adapter was stored as ``self._adapter`` while ``__init__`` named
    the parameter ``adapter``. SQLAlchemy builds a type's cache key by intersecting
    ``__init__`` parameter names with instance ``__dict__`` and discarding
    underscore-prefixed keys, so every instance collapsed to ``(PydanticJSON,)`` --
    and a statement declaring one type was decoded with another's adapter.
    """
    alpha = PydanticJSON(ALPHA_ADAPTER)
    beta = PydanticJSON(BETA_ADAPTER)
    assert alpha._static_cache_key != beta._static_cache_key
    assert PydanticJSON(ALPHA_ADAPTER)._static_cache_key == alpha._static_cache_key


def test_adapt_preserves_the_adapter() -> None:
    """``TypeEngine.adapt()`` must not return a conversion-dead column.

    ``util.constructor_copy`` reads ``__init__`` names off ``__dict__``; with the
    adapter hidden behind an underscore it rebuilt the type with no adapter at all --
    DDL-correct and unable to convert anything.
    """
    adapted = PydanticJSON(ALPHA_ADAPTER).adapt(PydanticJSON)
    assert adapted.adapter is ALPHA_ADAPTER


def test_postgresql_gets_jsonb_others_get_json() -> None:
    """``impl = types.JSON`` alone compiles to text-backed ``JSON`` on PostgreSQL."""
    column = PydanticJSON(ALPHA_ADAPTER)
    assert isinstance(column.load_dialect_impl(postgresql.dialect()), postgresql.JSONB)


def test_none_is_bound_as_sql_null() -> None:
    """``None`` must not become the JSON literal ``'null'``.

    With ``none_as_null=False`` -- SQLAlchemy's default -- ``WHERE col IS NULL``
    matches nothing and ``NOT NULL`` never trips.
    """
    column = PydanticJSON(ALPHA_ADAPTER)
    assert column.process_bind_param(None, postgresql.dialect()) is None
    assert column.impl_instance.none_as_null is True


def test_discriminated_union_round_trips_as_its_variant() -> None:
    """The reason the type exists: a union returns as the concrete variant."""
    column = PydanticJSON[Variant](VARIANT_ADAPTER)
    dialect = postgresql.dialect()
    wire = column.process_bind_param(Beta(label="x"), dialect)
    assert wire == {"kind": "beta", "label": "x"}
    restored = column.process_result_value(wire, dialect)
    assert isinstance(restored, Beta)
    assert restored.label == "x"


def test_adapter_is_required() -> None:
    """The adapterless constructor is gone, and with it a runtime failure mode."""
    with pytest.raises(TypeError):
        PydanticJSON()  # type: ignore[call-arg]  # the regression this test pins


def test_metadata_carries_naming_convention() -> None:
    """Without a convention, autogenerated migrations cannot drop what they create."""
    metadata = build_metadata()
    assert metadata.naming_convention == NAMING_CONVENTION
    assert build_metadata() is not metadata
